// <auto-generated />
using System;
using KnowledgeAssistant.Application.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeAssistant.Application.Data.Migrations
{
    [DbContext(typeof(KnowledgeContext))]
    [Migration("20260929202359_EmailUserIdIndex")]
    partial class EmailUserIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Emails.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "CreatedAt", "UserId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_Users_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Users_LastName");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Users_LastName_FirstName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "5 Grove Nook",
                            CreatedBy = 0,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            FirstName = "Zack",
                            IsDeleted = false,
                            LastName = "Bucci",
                            Location = "Huddersfield",
                            Postcode = "HD3 4UD"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "123 Main Street",
                            CreatedBy = 0,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            FirstName = "Bob",
                            IsDeleted = false,
                            LastName = "Smith",
                            Location = "Lincoln",
                            Postcode = "LN1 2AB"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "456 Oak Avenue",
                            CreatedBy = 0,
                            CreatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Duggy",
                            Location = "Manchester",
                            Postcode = "M1 3CD"
                        });
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("IX_UserCredentials_EmailAddress");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "zack.bucci@example.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENtrqYs0Oo8hJHojnX/bBRVRX1l9ExQGfMOScHNkp1JKfSvwHxJeBXvDpgLAVcHZVA==",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "john.smith@example.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENtrqYs0Oo8hJHojnX/bBRVRX1l9ExQGfMOScHNkp1JKfSvwHxJeBXvDpgLAVcHZVA==",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "john.duggy@example.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENtrqYs0Oo8hJHojnX/bBRVRX1l9ExQGfMOScHNkp1JKfSvwHxJeBXvDpgLAVcHZVA==",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.UserDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Emails.Email", b =>
                {
                    b.HasOne("KnowledgeAssistant.Domain.Entities.Users.User", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.UserCredential", b =>
                {
                    b.HasOne("KnowledgeAssistant.Domain.Entities.Users.User", "User")
                        .WithOne("Credentials")
                        .HasForeignKey("KnowledgeAssistant.Domain.Entities.Users.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.UserDocument", b =>
                {
                    b.HasOne("KnowledgeAssistant.Domain.Entities.Users.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeAssistant.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
